name: Container Practice

on: push

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: node:20

    steps:
      - name: Check Node Version
        run: node --version

      - name: Check NPM Version
        run: npm --version