name: Matrix Practice

on: push

jobs:
  test-os:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Show Operating System
        run: echo "Running on ${{ matrix.os }}"